package children;
// Generated Oct 28, 2018 5:58:06 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Children generated by hbm2java
 */
public class Children  implements java.io.Serializable {


     private Integer childId;
     private String childName;
     private Date birthDate;

    public Children() {
    }

	
    public Children(String childName) {
        this.childName = childName;
    }
    public Children(String childName, Date birthDate) {
       this.childName = childName;
       this.birthDate = birthDate;
    }
   
    public Integer getChildId() {
        return this.childId;
    }
    
    public void setChildId(Integer childId) {
        this.childId = childId;
    }
    public String getChildName() {
        return this.childName;
    }
    
    public void setChildName(String childName) {
        this.childName = childName;
    }
    public Date getBirthDate() {
        return this.birthDate;
    }
    
    public void setBirthDate(Date birthDate) {
        this.birthDate = birthDate;
    }

    String getName() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }




}
