package myhibernatetest;
// Generated Nov 29, 2018 6:25:22 AM by Hibernate Tools 3.6.0



/**
 * Customer generated by hbm2java
 */
public class Customer  implements java.io.Serializable {


     private int customerid;
     private String firstname;
     private String lastname;

    public Customer() {
    }

    public Customer(int customerid, String firstname, String lastname) {
       this.customerid = customerid;
       this.firstname = firstname;
       this.lastname = lastname;
    }
   
    public int getCustomerid() {
        return this.customerid;
    }
    
    public void setCustomerid(int customerid) {
        this.customerid = customerid;
    }
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }




}


