package myfamily;
// Generated Nov 29, 2018 8:34:17 PM by Hibernate Tools 3.6.0



/**
 * Family generated by hbm2java
 */
public class Family  implements java.io.Serializable {


     private int age;
     private String firstname;
     private String middlename;

    public Family() {
    }

    public Family(int age, String firstname, String middlename) {
       this.age = age;
       this.firstname = firstname;
       this.middlename = middlename;
    }
   
    public int getAge() {
        return this.age;
    }
    
    public void setAge(int age) {
        this.age = age;
    }
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }
    public String getMiddlename() {
        return this.middlename;
    }
    
    public void setMiddlename(String middlename) {
        this.middlename = middlename;
    }




}


